<?php

namespace repositories\front;

/**
 * AccountsProductsLikes
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsProductsLikes extends \Doctrine\ORM\EntityRepository
{
}
