<?php

namespace repositories\backend;

/**
 * AccountsDetail
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsDetail extends \Doctrine\ORM\EntityRepository
{
}
