<?php

namespace repositories\backend;

/**
 * AccountsLoginRecords
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsLoginRecords extends \Doctrine\ORM\EntityRepository
{
}
