<?php

namespace repositories\backend;

use Doctrine\ORM\Query;
use Registry;

/**
 * Accounts
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Accounts extends \Doctrine\ORM\EntityRepository
{
    /*
    避免複製，用reference
    */
    public function &findByAccountLogin(&$account) 
    {
        // 有效能需求，因此採最簡
        $qb_ = Registry::getManager('backend')->createQueryBuilder();
        $qb_->select("a.account, a.password")
           ->from('entities\backend\Accounts', 'a')
           ->where('a.account = :account')
           ->setParameter('account' , $account);

        $query_ = $qb_->getQuery()
            ->setHint(Query::HINT_FORCE_PARTIAL_LOAD, true);
        $result_ = $query_->getArrayResult();

        return $result_;
    }

}
