<?php

namespace repositories\backend;

use hahaha\hahaha_repositories_single_table_basic_trait;
use hahaha\hahaha_repositories_single_table_composite_trait;
use hahaha\hahaha_convert_doctrine_dql;
use Doctrine\ORM\Query;
use Registry;
use EntityManager;

/**
 * AccountsRelations
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsRelations extends \Doctrine\ORM\EntityRepository
{
    use hahaha_repositories_single_table_basic_trait;
    use hahaha_repositories_single_table_composite_trait;

    public $Alias = "a";
}
