<?php

namespace repositories\backend;

/**
 * AccountsRelations
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsRelations extends \Doctrine\ORM\EntityRepository
{
}
