<?php

namespace repositories\front;

/**
 * Accounts
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Accounts extends \Doctrine\ORM\EntityRepository
{
}
