<?php

namespace repositories\front;

/**
 * Migrationss
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Migrationss extends \Doctrine\ORM\EntityRepository
{
}
