<?php

namespace repositories\front;

/**
 * Products
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Products extends \Doctrine\ORM\EntityRepository
{
}
